#!/bin/sh

BINLOC=/usr/local/bin
LOGLOC=/var/log
PERSISTLOC=/etc/nflbot
SECLOC=$PERSISTLOC/secure
TEMPLOC=$PERSISTLOC/tmp
PYLIBLOC=/usr/local/lib/python3.5/dist-packages
DAEMONLOC=/etc/init.d


cp ./src/nflbot.py $BINLOC/
cp ./src/nflclean.sh $BINLOC/
cp ./src/dl_and_alter.sh $BINLOC/

mkdir -p $TEMPLOC
cp ./src/NFL.mp3 $PERSISTLOC/

mkdir -p $PERSISTLOC
touch $PERSISTLOC/lastID

mkdir -p $SECLOC
cp ./untracked/secure/* $SECLOC/

touch $LOGLOC/nflbot.log

cp -r ./src/tweepy $PYLIBLOC/

cp ./nfldaemon $DAEMONLOC/
chmod 755 $DAEMONLOC/nfldaemon
chown root:root $DAEMONLOC/nfldaemon
update-rc.d nfldaemon defaults
