#!/bin/sh
### BEGIN INIT INFO
# Provides:          nfldaemon
# Required-Start:    $remote_fs $syslog $network $time
# Required-Stop:     $remote_fs $syslog $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the nflbot
# Description:       Enable service provided by daemon.
### END INIT INFO
PATH=/usr/local/bin:/usr/bin
PYTHONPATH=/usr/local/lib/python3.5/dist-packages


case "$1" in

start)
	python3 $PATH/nflbot.py >> /var/log/nflbot.log 2>&1 &
	;;
stop)
	pkill nflbot.py
	;;
status)
	echo "Status unsupported"
	;;
restart)
	pkill nflbot.py
	python3 $PATH/nflbot.py>>/var/log/nflbot.log 2>&1 &
	;;
*)
	echo "start|stop|restart"


#python3 src/bot.py >> persist/bot.log 2>&1